namespace ReturnHome.Server.EntityObject
{
    public enum AnimationState : byte
    {
        AltLeftPunch = 0x20,
        AltRightPunch = 0x19,
        BoltShot = 0x21,
        Bow = 0x39,
        BowPull = 0x1f,
        Cheer = 0x3d,
        Crouching = 0x07,
        Die = 0x0e,
        Falling = 0x06,
        FightingStance = 0x11,
        HighKick = 0x35,
        Kick = 0x2b,
        Landing = 0x07,
        LeftBackHand = 0x1e,
        LeftHandCast = 0x25,
        LeftHandHit = 0x23,
        LeftHandStab = 0x1b,
        LeftPunch = 0x16,
        LeftUpperCut = 0x28,
        LookLeftRight = 0x0f,
        Point = 0x3c,
        PotThrow = 0x24,
        RightBackHand = 0x18,
        RightHandCast = 0x27,
        RightHandChop = 0x29,
        RightHandStab = 0x1c,
        RightLungePunch = 0x33,
        RightPunch = 0x17,
        RightUppercut = 0x32,
        Roundhouse = 0x34,
        Running = 0x03,
        SideStepLeft = 0x0a,
        SideStepRight = 0x0b,
        SlowRightHand = 0x3f,
        SquatFreeze = 0x40,
        SwimFast = 0x0c,
        SwimRightPunch = 0x2c,
        SwimSlow = 0x0d,
        TakeHit = 0x22,
        TurningInPlaceLeft = 0x04,
        TurningInPlaceRight = 0x05,
        TwoHandCast = 0x26,
        TwoHandDownSlash = 0x2a,
        TwoHandStab = 0x1d,
        TwoHandSwingLeftRight = 0x1a,
        Walking = 0x01,
        WalkingBackwards = 0x02,
        Wave = 0x38
    }
}
