from sqlalchemy import Column, Integer, String, Float
from app.core.sql_app.database import Base


class NPCInfo(Base):
    __tablename__ = "npcs"

    id = Column(Integer, unique=True, primary_key=True, index=True)
    npc_name = Column(String, unique=True)
    x_coord = Column(Float)
    y_coord = Column(Float)
    z_coord = Column(Float)
    facing = Column(Float)
    world = Column(Integer)
    hp = Column(Integer)
    modelid = Column(Integer)
    size = Column(Integer)
    primary_weapon = Column(Integer)
    secondary_weapon = Column(Integer)
    shield = Column(Integer)
    torso = Column(Integer)
    forearm = Column(Integer)
    gloves = Column(Integer)
    legs = Column(Integer)
    feet = Column(Integer)
    head = Column(Integer)
    hair_color = Column(Integer)
    hair_length = Column(Integer)
    hair_style = Column(Integer)
    face = Column(Integer)
    robe_style = Column(String)
    race = Column(String)
    npc_level = Column(Integer)
    npc_type = Column(Integer)
    npc_id = Column(Integer)

class ItemInfo(Base):
    __tablename__ = "itempattern"

    patternid = Column(Integer, unique=True, primary_key=True, index=True)
    itemname = Column(String)
    patternfam = Column(Integer, default=0)
    itemicon = Column(Integer, default=1)
    equipslot = Column(Integer, default=0)
    trade = Column(Integer, default=0)
    rent = Column(Integer, default=0)
    attacktype = Column(Integer, default=0)
    weapondamage = Column(Integer, default=0)
    levelreq = Column(Integer, default=1)
    maxstack = Column(Integer, default=1)
    maxhp = Column(Integer, default=100)
    duration = Column(Integer, default=50)
    classuse = Column(Integer, default = 32767)
    raceuse = Column(Integer, default = 1023)
    procanim = Column(Integer, default=0)
    lore = Column(Integer, default=0)
    craft = Column(Integer, default=0)
    itemdesc = Column(String, default="This is just placeholder text, please update.")
    model = Column(Integer, default=0)
    color = Column(Integer, default=0)
    str = Column(Integer, default=0)
    sta = Column(Integer, default=0)
    agi = Column(Integer, default=0)
    wis = Column(Integer, default=0)
    dex = Column(Integer, default=0)
    cha = Column(Integer, default=0)
    intelligence = Column(Integer, default=0)
    HPMAX = Column(Integer, default=0)
    POWMAX = Column(Integer, default=0)
    PoT = Column(Integer, default=0)
    HoT = Column(Integer, default=0)
    AC = Column(Integer, default=0)
    PR = Column(Integer, default=0)
    DR = Column(Integer, default=0)
    FR = Column(Integer, default=0)
    CR = Column(Integer, default=0) 
    LR = Column(Integer, default=0)
    AR = Column(Integer, default=0)
    weaponproc = Column(Integer, default=0)
    fish = Column(Integer, default=0) 
