name: ci

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Starts the compose up, creating all of the docker containers in the pipeline
      - name: Start containers
        run: |
          docker-compose up -d mariadb
          docker-compose up -d authentication-server
          docker-compose up -d returnhome-server
          docker-compose up -d gohttpserver
          docker-compose up -d dnsmasq || true

      # Stops the containers for cleanup in the pipeline
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
